// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SharedLibrary.Infrastructure.Migrations
{
    [DbContext(typeof(CivicHubDbContext))]
    [Migration("20260204123635_InitialKioskSchema")]
    partial class InitialKioskSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvKioskDepartment");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvKioskDetail");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KioskId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KioskId");

                    b.ToTable("InvKioskLanguage");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("InvKioskDetailId")
                        .HasColumnType("int");

                    b.Property<int>("KioskId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvKioskDetailId");

                    b.ToTable("InvKioskService");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskSessionUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserActiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UserLastSession")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserPhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvKioskSessionUser");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskTrackingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KioskId")
                        .HasColumnType("int");

                    b.Property<int?>("KioskServiceId")
                        .HasColumnType("int");

                    b.Property<string>("SessionActivity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SessionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KioskId");

                    b.HasIndex("KioskServiceId");

                    b.HasIndex("SessionUserId");

                    b.ToTable("InvKioskTrackingDetail");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskLanguage", b =>
                {
                    b.HasOne("SharedLibrary.Domain.Entities.InvKioskDetail", "Kiosk")
                        .WithMany("Languages")
                        .HasForeignKey("KioskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiosk");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskService", b =>
                {
                    b.HasOne("SharedLibrary.Domain.Entities.InvKioskDetail", null)
                        .WithMany("Services")
                        .HasForeignKey("InvKioskDetailId");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskTrackingDetail", b =>
                {
                    b.HasOne("SharedLibrary.Domain.Entities.InvKioskDetail", "Kiosk")
                        .WithMany()
                        .HasForeignKey("KioskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Domain.Entities.InvKioskService", "KioskService")
                        .WithMany()
                        .HasForeignKey("KioskServiceId");

                    b.HasOne("SharedLibrary.Domain.Entities.InvKioskSessionUser", "SessionUser")
                        .WithMany("TrackingDetails")
                        .HasForeignKey("SessionUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiosk");

                    b.Navigation("KioskService");

                    b.Navigation("SessionUser");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskDetail", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("SharedLibrary.Domain.Entities.InvKioskSessionUser", b =>
                {
                    b.Navigation("TrackingDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
